version: '3.8'
services:
  world_of_games2:
    container_name: world_of_games2
    build: .
    ports:
     - "8888:8777"
     nvironment:
      - ELK_HOST=logstash
    depends_on:
      - logstash
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped

    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: ${CONTAINER_PORT}
    volumes:
      - ./Scores.txt:/app/Scores.txt:rw
      - ./templates:/app/templates:ro
      - ./modules:/app/modules:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8777 || exit 1"]
      interval: 10s
      retries: 15
      start_period: 10s















