services:
  world_of_games2:
    container_name: world_of_games2
    build: .
    ports:
     - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: ${CONTAINER_PORT}
    volumes:
      - ./Scores.txt:/app/Scores.txt:rw
      - ./templates:/app/templates:ro
      - ./modules:/app/modules:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8777 || exit 1"]
      interval: 10s
      retries: 15
      start_period: 10s













