name: Auto Commit

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # allows manual run
permissions: 
  contents: write

jobs:
  autocommit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Step 2: Set up Python (if you want auto-formatting or deps update)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort autoflake

      # Step 4: Run auto-formatters (you can adjust)
      - name: Format code
        run: |
          black .
          isort .
          autoflake --in-place --remove-unused-variables --remove-all-unused-imports -r .

      # Step 5: Commit & Push changes
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "chore: auto-format & update [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }} HEAD:main
